### ISSUE TITLE
Edge case when stats::dist gives an output while rdist gives a NaN for Euclidean

### ISSUE THREAD

**Issue by JohnMCMa** [blasern/rdist#2]
I'm not knowledgeable about how floating-point math is handled in rdist, but it appear to me that if the two row's difference is smaller than `double.eps`, there's a risk that the rdist will give out `NaN`'s.
    errorSample <- read.csv ("errorSample.txt")
    
    dist (errorSample, method="euclidean")
                  IFNA8
    IFNA17 2.116552e-15
    rdist (errorSample, metric="euclidean")
        1
    2 NaN
    
    sort (table (errorSample [1, ] - errorSample[2, ]))
    -8.32667268468867e-17 -4.16333634234434e-17 -2.08166817117217e-17 -1.04083408558608e-17 -2.60208521396521e-18 
                    1                     1                     1                     1                     1 
    -2.27682456221956e-18 -1.62630325872826e-18 -1.30104260698261e-18  -1.0842021724855e-18 -6.50521303491303e-19 
                    1                     1                     1                     1                     1 
    -5.42101086242752e-19 -3.52365706057789e-19  2.16840434497101e-19  6.50521303491303e-19  9.75781955236954e-19 
                    1                     1                     1                     1                     1 
     4.33680868994202e-19  1.30104260698261e-18  1.04083408558608e-17  4.16333634234434e-17 -3.33066907387547e-16 
                    2                     2                     2                     2                     4 
    -1.66533453693773e-16 -8.67361737988404e-19  5.55111512312578e-17  1.11022302462516e-16  2.08166817117217e-17 
                    4                     5                     5                     5                     6 
     8.67361737988404e-19  1.73472347597681e-18 -1.73472347597681e-18 -3.46944695195361e-18 -2.22044604925031e-16 
                   10                    16                    19                    21                    42 
     2.77555756156289e-17 -6.93889390390723e-18 -2.77555756156289e-17  3.46944695195361e-18 -1.38777878078145e-17 
                   42                    45                    59                    67                    68 
    -5.55111512312578e-17 -1.11022302462516e-16  6.93889390390723e-18  1.38777878078145e-17                     0 
                   72                   113                   174                   231                   412 

0 is probably an acceptable answer for situations like this, but hardly `NaN`.
[errorSample.txt](https://github.com/blasern/rdist/files/994319/errorSample.txt)

**Comment by blasern** [comment]
Thanks @JohnMCMa for letting me know about the bug.
