### ISSUE TITLE
Self-defined functions

### ISSUE THREAD

**Issue by ywhcuhk** [blasern/rdist#3]
First, thank you so much for developing such a useful and really **fast** package. It already contains a long list of common distance functions.  But I wonder if you could add the feature that allows the user to supply a self-defined function that would return a distance scalar between 2 vectors. 

Thanks!

**Comment by blasern** [comment]
There's no obvious way to make this fast, since it will have to call the function n^2 times. That's why all distance functions should be vectorized. But I can implement a slow version of it.

**Comment by ywhcuhk** [comment]
Would it be fast I supply a Rcpp function? The distance calculation shouldn't be very complicated.

**Comment by blasern** [comment]
The problem is that we cannot compile the vector-distance function and the pairwise distance functions together. Therefore there will always be an overhead. The way I implemented it now will work but cannot compare to the speed of the other functions.

**Comment by ywhcuhk** [comment]
Thanks! It's okay if it's slow, as long as it's working. So I should pull the most recent development version from Github? And could you please briefly introduce the API or a simple example would suffice.

**Comment by blasern** [comment]
Yes, you should install the package directly from github ([see here for instructions](https://github.com/blasern/rdist)). There are some examples in the [tests](https://github.com/blasern/rdist/blob/master/tests/testthat/test-user-defined.R).

**Comment by ywhcuhk** [comment]
@blasern Thanks a lot for the new feature!
