### ISSUE TITLE
Package not downloading on RStudio Server

### ISSUE THREAD

**Issue by AlexWang18** [blasern/rdist#4]
The package works fine for me locally on Windows 10 on R Studio. However when I try to download it on RStudio Server I get the following error. 
```
/bin/ld: cannot find -llapack
/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
make: *** [rdist.so] Error 1
ERROR: compilation failed for package ‘rdist’
  removing ‘/ihome/hpark/alw245/R/x86_64-pc-linux-gnu-library/4.0/rdist’
Warning in install.packages :
  installation of package ‘rdist’ had non-zero exit status
```
My VM is running RedHat Enterprise. I've tried downloading straight from source as well and received the same error.

**Comment by blasern** [comment]
This sounds like an issue with RcppArmadillo. Have you successfully installed RcppArmadillo?

**Comment by AlexWang18** [comment]
Your right. I run into the same issue trying to install RcppArmadillo. I think I need to manually install llpack through yum but I don't have admin privileges.

**Comment by janxkoci** [comment]
FYI - RcppArmadillo can be installed without admin privileges using `conda install conda-forge::r-rcpparmadillo` (it's also in `r` and Anaconda's `default` channels, but I prefer the community `conda-forge` channel). See here: https://anaconda.org/channels/conda-forge/packages/r-rcpparmadillo/overview

In fact - `conda-forge` has `rdist` too, so you can just use:

```bash
conda install conda-forge::r-rdist
```

Hope it helps in the future 😉
